receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
  fluentforward:
    endpoint: 0.0.0.0:8006

exporters:
  jaeger_thrift:
    url: "http://jaeger:14268/api/traces"
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  elasticsearch:
    endpoints:
      - "http://elasticsearch:9200"

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [zipkin, jaeger_thrift, logging]
      processors: [batch]
    logs:
      receivers: [fluentforward]
      exporters: [elasticsearch]
      processors: [batch]
